name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/app
            git clone https://github.com/sadamtheCoder786/2212266-devops-project ~/app
            cd ~/app

            cat > .env << 'ENVEOF'
            POSTGRES_USER=devuser
            POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
            POSTGRES_DB=devdb
            DATABASE_URL=postgresql://devuser:${{ secrets.DB_PASSWORD }}@db:5432/devdb
            STUDENT_REG_NO=${{ secrets.STUDENT_REG_NO }}
            ENVEOF

            docker compose -f docker-compose.prod.yml down --remove-orphans 2>/dev/null || true
            docker compose -f docker-compose.prod.yml up --build -d

            sleep 15
            curl -f http://localhost:8000/health || exit 1